### ISSUE TITLE
run_busco.py failed for conda busco installation

### ISSUE THREAD

**Issue by nursyahr** [ablab/rnaquast#13]
Dear rnaquast authors, 

Thank you for developing this tool.

I am trying to assess quality of my de novo transcriptome with the following command: 
```rnaQUAST.py --transcripts file.cds  --busco_lineage busco_downloads/lineages/eudicots_odb10```

I have installed and added GeneMark to `$PATH`.
Using the following versions installed via bioconda on ubuntu.
```
busco                     5.3.2              pyhdfd78af_0    bioconda
rnaquast                  2.0.1                         0    bioconda
```
I'm unable to run the BUSCO step despite having it installed via conda. Do I need to install the software directly to provide the run_busco.py file? Or can I direct it to the one installed by conda somehow?
Here is my log: [rnaQUAST.log](https://github.com/ablab/rnaquast/files/8560260/rnaQUAST.log)

Thank you!

**Comment by andrewprzh** [comment]
Hi

I presume that installation via conda should work just fine. Could you try the latest rnaQUAST version 2.2.2? 
2.0.1 is 2 years old and I recall it had some problems with new BUSCO versions.

If the error occurs in the new version, send me also these files:
`logs can be found in /home/syahirah/plant20/MS_rnaq/logs/MS_trinity.Trinity.okay.Trinity.cds.busco.out.log and /home/syahirah/plant20/MS_rnaq/logs/MS_trinity.Trinity.okay.Trinity.cds.busco.err.log.`

All the best
Andrey

**Comment by Anto007** [comment]
@andrewprzh I was unable to find version 2.2.2 on conda (as you've mentioned here). Version 2.2.1 is the latest one that is available on conda and busco fails to work on it irrespective of whether the latest BUSCO 5.4.3 or the older BUSCO 4.1.4 is made available via conda

**Comment by andrewprzh** [comment]
Please reopen if you still need assistance.

Best
Andrey

**Comment by seashore001x** [comment]
This problem happens again in 2.3 version of rnaQUAST from conda

**Comment by andrewprzh** [comment]
@seashore001x could you send error logs please and command you used for installation and running rnaQUAST?
