### ISSUE TITLE
python3

### ISSUE THREAD

**Issue by Zethson** [ablab/rnaquast#2]
Hi,

python2 is EOL. I would like to kindly request a python 3 version.

**Comment by andrewprzh** [comment]
Hi

Took us some time to get back to this project. Finally, python3 support https://github.com/ablab/rnaquast/releases/tag/v.2.0.0

**Comment by andrewprzh** [comment]
Hi!

Thanks a lot for the notice. Unfortunately, some servers still use python2 :/
However, I think we will remove python2 support at some point.

Best
Andrey
