### ISSUE TITLE
Comparing multiple rnaQUAST reports

### ISSUE THREAD

**Issue by SimonHegele** [ablab/rnaquast#25]
Many thanks for this tool!

It ran flawlessly and the output is very detailed and provides many informative metrics.
I wrote a small tool to make comparing different reports easier.
(https://github.com/SimonHegele/rnaQAUSTcompare)

**Comment by andrewprzh** [comment]
@SimonHegele 

Great, I'll add a link to README, this can be useful for the users!

Best
Andrey
