### ISSUE TITLE
'dict_keys' object is not subscriptable

### ISSUE THREAD

**Issue by summerXiaHan** [ablab/rnaquast#4]
Hi, I run rnaQUAST.py successfully several days ago, but now i run with errors no matter how I set the $PYTHONPATH (I had tried for python2.7, python3.5, python3.6). So I install anaconda, and then use conda to create a python3.6 environment, and after i activate the environment, i install rnaQUAST.py and run 'rnaQUAST.py --test' successfully. 
However,  when I try on the real data, error occurs like:
<img width="1280" alt="屏幕快照 2020-08-27 下午12 23 11" src="https://user-images.githubusercontent.com/43634319/91384407-17622080-e861-11ea-935b-67578bcb28be.png">
my command is:
`rnaQUAST.py --transcripts Bridger.fasta --reference $ref --gtf $gtf -o bridger -t 30 --blat`
Would you tell me how to deal with it?
Thanks!

**Comment by summerXiaHan** [comment]
[rnaQUAST.log](https://github.com/ablab/rnaquast/files/5134069/rnaQUAST.log)

**Comment by andrewprzh** [comment]
Hi!

That looks like a bug in the new version. Could you try gmap instead of blat in meantime? (simply remove --blat option).

In general we see that gmap gives more consistent results.

All the best
Andrey

**Comment by andrewprzh** [comment]
Yes, the bug is in general/parallel_blat_run.py at line 84 as indicated:
You may change
    id_transcripts = transcripts_dict.keys()[:]
to
    id_transcripts = list(transcripts_dict.keys())  

Bugfix release will be out soon, thanks for reporting!
